name: MATLAB Unit Tests

on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run MATLAB Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: latest

      - name: Run MATLAB build and tests
        uses: matlab-actions/run-build@v2
        with:
          command: "results = runtests('TestProcessCSVData'); assert(~any([results.Failed]), 'One or more tests failed.');"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestProcessCSVDataResults.mat

